/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;
import java.util.Date;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
/**
 *
 * @author porta
 */
public class crearPDF extends javax.swing.JFrame {
        int id;
        String nombre_archivo;
        String tabla;
        Date fecha = new Date();
        DateFormat hora= new SimpleDateFormat("hh:mm");
        DateFormat dia = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form crearPDF
     */
    public crearPDF() {
        initComponents();
          this.getContentPane().setBackground(Color.GRAY);
    }
    
    public void datos(int id, String tabla){
        this.id= id;
        this.tabla= tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPane = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnSubir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creación de PDF");

        txtPane.setColumns(20);
        txtPane.setRows(5);
        jScrollPane1.setViewportView(txtPane);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Escribe aqui tu información.");

        btnSubir.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btnSubir.setText("Subir");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSubir)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubir)
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
      
            try {
                generar();
                insertar(dia.format(fecha), hora.format(fecha) , nombre_archivo, "pdf");
                
                //  System.out.print(dF.format(fecha)+ " hora "+ hora.format(fecha) );

                dispose();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(crearPDF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(crearPDF.class.getName()).log(Level.SEVERE, null, ex);
            }
     
 
        
    }//GEN-LAST:event_btnSubirActionPerformed

    
    
    public void insertar ( String dia , String hora, String nombre, String tipo) {
      Connection con=null;
      Statement stmnt = null;
      String sql=null;
    try {
     
        //tsbla solo sera ip o so 
        //las
        Class.forName("org.postgresql.Driver");
        con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "1234");
        stmnt = con.createStatement();
      //  JOptionPane.showMessageDialog(null, "ingresado correctamente");
        switch(tabla){
            case "documentos":
                 stmnt.executeUpdate("insert into documentos (id, nombre, tipo, fecha, hora) "
                + "values('" +id + "','"+nombre+"', '"+tipo+ "', '"+dia+"','"+ hora +"');");
                break;
            case "tareas":
                 Tarea aux= new Tarea();
                 aux.setVisible(true);
                 aux.guardar(nombre, id);
                 
                break;
                
                   
        }
        
        stmnt.close();
        // con.commit();
        //JOptionPane.showMessageDialog(null, "agregado");
    }  catch (ClassNotFoundException ex) {      
                Logger.getLogger(crearPDF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(crearPDF.class.getName()).log(Level.SEVERE, null, ex);
            }      
       

      
    
}
    
    
    
   public void generar () throws FileNotFoundException, DocumentException{
           JFileChooser sel= new JFileChooser();
           int opc= sel.showSaveDialog(null);
           try{
               OutputStream txt= new FileOutputStream(sel.getSelectedFile());
               Document doc= new Document ();
               PdfWriter.getInstance(doc, txt);
               doc.open();
               doc.add(new Paragraph (txtPane.getText()));
               
               nombre_archivo= sel.getSelectedFile().getName();
               doc.close();
               txt.close();
               
           }catch(Exception ex){}
 
           
           
   }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearPDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPane;
    // End of variables declaration//GEN-END:variables
}
